### ISSUE TITLE
CustomBtn item in pop-up form, add close parameter

### ISSUE THREAD

**Issue by tqtq-Wang** [pqcqaq/qc-components#1]
![微信图片_20240604162130](https://github.com/pqcqaq/qc-components/assets/113757315/b8805a77-54ae-4844-9df7-3aeeec3e65c5)

**Comment by pqcqaq** [comment]
thanks, the new feature added in version 0.2.13.
![image](https://github.com/pqcqaq/qc-components/assets/35625470/3485d47e-ce19-4b8f-9ddc-74b6635a43e1)
